wanted to use URLs
koaning/bulk pull request #41
Opened 2022-12-04 19:17 UTC by zbenmo

Played with Quick Draw - Mona Lisa, repeated your Eiffel experiment. - Wanted to use URLs directly to the web server as you have suggested. I have not used Prodigy.

Really interesting clusters with the Mona Lisa DS.

![quick draw Mona Lisa](https://user-images.githubusercontent.com/1571438/205510613-6aa1d636-5e6b-4c7e-a040-ea560628bad6.png)

WKR,
Oren
--

2022-12-05 09:37 UTC, koaning commented
Interesting! Have you tried running this locally? While I don't mind adding this feature, part of me does worry that it could be slow. Partially because local images are always faster, but also because the current implementation doesn't use async. Could you comment on the performance?

2022-12-05 09:43 UTC, zbenmo commented
Hi,

It was reasonable (a minute or a few) for ~3000 quick-draw images.

Mostly wanted to brag about me trying your package and finding interesting
pattern in the Mona Lisa dataset. Will not be offended if feature not
merged.


WKR,
Oren



On Mon, Dec 5, 2022 at 10:37 AM vincent d warmerdam <
***@***.***> wrote:

> Interesting! Have you tried running this locally? While I don't mind
> adding this feature, part of me does worry that it could be slow. Partially
> because local images are always faster, but also because the current
> implementation doesn't use async. Could you comment on the performance?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/koaning/bulk/pull/41#issuecomment-1337031834>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAL7U3S6LY37REEALIM3GJTWLWZUVANCNFSM6AAAAAASTQXM5I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-05 09:47 UTC, koaning commented
I actually do really like the idea and it's super cool to see that you've gone ahead and replicated the video! I'm definately interested in the PR, it's just that I want to make sure it's not a performance hog before I recommend people to use this feature. 

Could you add a GIF of what the experience is like on your end? I might also be able to replicate it myself but I might not have time for that this week. 

On a personal note; you've found a really cool set of clusters here that's totally worth a blog-post. If you haven't started a blog yet; this would make a cool entry.

2022-12-05 09:54 UTC, koaning commented
If you're not planning to blog about it, would you mind if I tweet/toot about this? I _really_ like this example.

2022-12-05 10:01 UTC, zbenmo commented
Okay, so now I have an incentive to blog it. I will and share.

On Mon, Dec 5, 2022 at 10:55 AM vincent d warmerdam <
***@***.***> wrote:

> If you're not planning to blog about it, would you mind if I tweet/toot
> about this? I *really* like this example.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/koaning/bulk/pull/41#issuecomment-1337052008>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAL7U3U75F7I7LKMI7K52D3WLW3XNANCNFSM6AAAAAASTQXM5I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-05 10:11 UTC, koaning commented
If you're looking for software; I heard great things about `hugo` but my own https://koaning.io blog is just a script that generates a blog via `mkdocs`.

2022-12-05 13:28 UTC, zbenmo commented
Thanks.

https://zbenmo.medium.com/bulk-labelling-the-mona-lisa-98acd5ea8ce2

I will look into hugo in the future.


WKR,
Oren

On Mon, Dec 5, 2022 at 11:11 AM vincent d warmerdam <
***@***.***> wrote:

> If you're looking for software; I heard great things about hugo but my
> own https://koaning.io blog is just a script that generates a blog via
> mkdocs.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/koaning/bulk/pull/41#issuecomment-1337076396>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAL7U3SOL3F2D7FNMRHUUVTWLW5W3ANCNFSM6AAAAAASTQXM5I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-03 15:27 UTC, koaning commented on bulk/cli/image.py
> +            enc_str = base64.b64encode(image_file.read()).decode("utf-8")
Wouldn't it be a lot less computationally intensive to have the frontend do this fetching? Something like:

```python
if path.startswith('http'):
     return f'<img style="object-fit: scale-down;" width="100%" height="100%" src="{path}">'
```

2023-01-03 15:27 UTC, koaning requested changes
I think this can be a whole lot quicker, but lets discuss!

2023-01-28 09:35 UTC, koaning approved these changes
LGTM!

2023-01-28 09:39 UTC, merged