Image resizing
koaning/bulk pull request #49
Opened 2023-02-01 15:38 UTC by CGCooke

Added a command line option to convert images to thumbnails on startup.

This helps to reduce the memory requirements where there is a large dataset with large images.

Example usage:
`python -m bulk image my_dataset.csv --thumbnail`

2023-02-01 16:58 UTC, koaning commented
I'm not 100% sure if I'd place it there. 

Maybe instead have it live in `python -m bulk utils resize`? 

I also wonder if this is a batch job you'd want to run before running `python -m bulk image`? Doesn't it become super slow to do resizing before loading it into bulk?

2023-02-02 14:32 UTC, koaning commented
Also, a unit test would be nice!

2023-02-02 14:42 UTC, CGCooke commented
- Maybe instead have it live in python -m bulk utils resize?
This sounds like a good idea,


- I also wonder if this is a batch job you'd want to run before running python -m bulk image? Doesn't it become super slow to do resizing before loading it into bulk?

It is slower, however, once you get up to a certain scale, (thousands of HD images), the dataset will not load at all, without being resized.

I think it should be a batch job, and then place the thumbnails into a thumbnail folder?

2023-02-02 15:05 UTC, koaning commented
>  into a thumbnail folder?

I'd require the user to pass a folder explicitly. And if said folder already exists then the user should be prompted to confirm.

2023-02-09 08:52 UTC, CGCooke commented
"And if said folder already exists then the user should be prompted to confirm.",
I'm not sure how to do this, but I've updated the code on the branch with the feedback.

2023-02-09 11:57 UTC, koaning commented on README.md
> +python -m bulk image ready.csv --thumbnail-path temp
Can't the `ready.csv` file have path that point to the thumbnail path? It occurs to me that it is the users responsibility to point to the right image path and to provide the correct x,y coordinates for them.

2023-02-09 11:58 UTC, koaning commented on bulk/cli/util.py
> +    os.system(f"mkdir {thumbnail_paths}")
I prefer to use `Pathlib` here, but that's also something I can do post-PR.

2023-02-09 11:59 UTC, koaning requested changes
Left one comment on the `--thumbnail-path` mechanic. 

Also, would it be possible to add a small unit test for this? Maybe just a smoke test?

2023-02-09 12:00 UTC, koaning commented on bulk/cli/util.py
> +    os.system(f"mkdir {thumbnail_paths}")
Same with the comment on the prompt, by the way. That's also something I can pickup.

2023-02-11 13:47 UTC, koaning commented
If you prefer, I can wrap up this PR on my side. I'm planning on switching command line backends anyway and that way you can still get your feature in, it's just that I'll wrap it up sometime later this week.

2023-02-15 18:33 UTC, CGCooke commented
> If you prefer, I can wrap up this PR on my side. I'm planning on switching command line backends anyway and that way you can still get your feature in, it's just that I'll wrap it up sometime later this week.

Thanks, that's really appreciated. I was having a little trouble getting the testing to work properly.

2023-02-16 11:35 UTC, koaning commented
No worries. I'll pick this up sometime later, but I'll make sure it gets included somehow!

2023-02-21 02:54 UTC, merged